name: PR Checklist Create
on:
  pull_request:
    types: [opened]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
            <!-- PR CHECKLIST -->
            - [ ] Does your PR title include the JIRA ticket number?
            - [ ] Did you write all the tests that need to be written for this change?
            - [ ] Is everything that should be wrapped in a feature flag properly gated?
            - [ ] Did you file any followup tickets that need to be filed?
              `
            })
