name: PR Checklist Validate
on:
  issue_comment:
    types: [edited]

jobs:
  validate-comment:
    if: github.event.issue.pull_request && github.event.issue.state == 'open' && contains(github.event.comment.body, '<!-- PR CHECKLIST -->')
    runs-on: ubuntu-latest
    steps:
      - name: Get Sha
        id: get-sha
        run: echo "sha=$(gh pr view ${{ github.event.issue.number }} --repo ${{ github.repository }} --json headRefOid --jq '.headRefOid')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/github-script@v7
        with:
          script: |
            const unfinishedChecklist = context.payload.comment.body.match(/- \[ \] (.+)/g) ?? []

            if (unfinishedChecklist.length > 0) {
              core.setFailed();
              await core.summary
                .addHeading('Unfinished checklist items found:')
                .addList(unfinishedChecklist)
                .write();
            }
      - name: Set latest commit status as ${{ job.status }}
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ steps.get-sha.outputs.sha }}',
              state: '${{ job.status }}',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Make sure you have completed the PR Checklist',
              context: '${{ github.workflow }}',
            });
