name: PR Checklist Validate
on:
  issue_comment:
    types: [edited]

jobs:
  validate-comment:
    if: github.event.issue.pull_request && github.event.issue.state == 'open' && contains(github.event.comment.body, '<!-- PR CHECKLIST -->')
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch
        id: get-sha
        run: echo "sha=$(gh pr view $PR_NO --repo $REPO --json headRefOid --jq '.headRefOid')" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ steps.get-branch.outputs.branch }}
      - uses: actions/github-script@v7
        with:
          script: |
            const unfinishedChecklist = context.payload.comment.body.match(/- \[ \] (.+)/g)
              .filter(checklistItem => !checklistItem.includes('[x]'));

            if (unfinishedChecklist.length > 0) {
              core.setFailed(`Unfinished checklist items found:\n${unfinishedChecklist.join('\n')}`);
            }
      - name: Set latest commit status as ${{ job.status }}
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ steps.get-sha.outputs.sha }}',
              state: '${{ job.status }}',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: 'Make sure you have completed the PR Checklist',
              context: '${{ github.workflow }}',
            });
